baseURL = 'http://example.org/'
languageCode = 'en-gb'
title = 'Eastside Recovery'

theme = 'puppet'

[params]
img_home = "img/img1.jpg"
img_404 = "img/404-bg.jpg"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "contact"
name = "Contact Us"
url = "/contact/"
weight = 10