baseURL = 'https://thource.github.io/eastside-recovery'
languageCode = 'en-gb'
title = 'Eastside Recovery'

theme = 'puppet'

[params]
img_home = "img/img4.jpg"
img_404 = "img/404-bg.jpg"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -99
[[menu.main]]
identifier = "contact"
name = "Contact Us"
url = "/contact/"
weight = 10